sudo: false
language: python
python: "3.5"
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.6
      env: TOX_ENV=py36-codestyle
    - env: TOX_ENV=py27-codestyle
    - python: pypy
      env: TOX_ENV=pypy
    - python: pypy3
      env: TOX_ENV=pypy3
    - env:
        - TOX_ENV=jython
        - PYENV_VERSION=jython-2.7.0
before_install:
  - |
      if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.3.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi
install: pip install tox
script: tox -e $TOX_ENV
cache:
  - pip
  - directories:
      $HOME/.pyenv_cache

notifications:
  email: false
